name: CI
on: [push]
jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu
            runs-on: ubuntu-latest
          #- name: MacOS
          #  runs-on: macos-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup upterm ssh session
      #uses: lhotari/action-upterm@dev
      uses: ./.github/actions/ssh-access
      with:
        secure-access: false
        #limit-access-to-actor: true
        #limit-access-to-users: lhotari,lhotari
    - name: Wait for ssh connection
      uses: ./.github/actions/ssh-access
      with:
        action: wait
        timeout: 120
