name: CI
on: [push]
jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: MacOS
            runs-on: macos-10.15
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v2
    - uses: lhotari/gh-actions-artifact-client@master
    - name: Setup upterm ssh session
      uses: ./.github/actions/ssh-access
      with:
        limit-access-to-actor: true
        limit-access-to-users: CamJN
    - name: Wait for ssh connection
      uses: ./.github/actions/ssh-access
      with:
        action: wait
        timeout: 120
